name: matrix_sdk
description: An SDK written in Dart to connect to Matrix, the federated communication protocol.
homepage: https://pattle.dev/pattle/library/matrix-dart-sdk
repository: https://pattle.dev/pattle/library/matrix-dart-sdk
issue_tracker: https://pattle.dev/pattle/library/matrix-dart-sdk/issues
documentation: ""
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  quiver: ^3.1.0
  meta: ^1.7.0
  http: ^0.13.4
  chopper: ^4.0.6
  ffi: ^2.0.1
  async: ^2.8.2
  synchronized: ^3.0.0+2
  collection: ^1.16.0
  drift: 1.7.1
  logger: ^1.1.0
  sqlite3_flutter_libs: ^0.5.8
  mime: ^1.0.2
  image: ^3.2.0
  pedantic: ^1.11.1

dev_dependencies:
  build_runner: ^2.2.0
  precise_pattle: ^1.0.5
  effective_dart: ^1.3.2
  test: ^1.21.4
  mockito: ^5.2.0
  chopper_generator: ^4.0.6
  dotenv: ^4.0.1
  drift_dev: 1.7.0
