name: matrix_sdk
description: An SDK written in Dart to connect to Matrix, the federated communication protocol.
homepage: https://pattle.dev/pattle/library/matrix-dart-sdk
repository: https://pattle.dev/pattle/library/matrix-dart-sdk
issue_tracker: https://pattle.dev/pattle/library/matrix-dart-sdk/issues
documentation: ""
publish_to: none

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  quiver: ^3.0.1
  meta: ^1.3.0
  http: ^0.13.3
  chopper: ^4.0.1
  ffi: ^1.1.2
  async: ^2.7.0
  synchronized: ^3.0.0
  collection: ^1.15.0
  moor: ^4.4.1
  #moor_ffi: ^0.8.0
  sqlite3_flutter_libs: ^0.5.0
  mime: ^1.0.0
  image: ^3.0.2
  pedantic: ^1.11.0

dev_dependencies:
  build_runner: ^2.0.4
  precise_pattle: ^1.0.5
  effective_dart: ^1.3.1
  test: ^1.17.8
  mockito: ^5.0.10
  chopper_generator: ^4.0.1
  dotenv: 3.0.0
  moor_generator: ^4.4.0